### ISSUE TITLE
Help! How do I run rpycg?

### ISSUE THREAD

**Issue by Wulfy6** [lure0xaos/rpycg#1]
How do I run rpycg I don't see an executable or anything. Thank you for your help :)

**Comment by lure0xaos** [comment]
i'm not sure how to make executable on github, but after you build it from maven "`mvn clean package`" you should be able to run it just as simple as "`java -jar RPyCG.jar`"

**Comment by lure0xaos** [comment]
please take a look at [releases](https://github.com/lure0xaos/rpycg/releases)
